class AccountRole:
    CUSTOMER = "CUSTOMER"
    OWNER = "OWNER"


class AccountStatus:
    ACTIVE = "ACTIVE"
    LOCKED = "LOCKED"
    WITHDRAWN = "WITHDRAWN"


class ProductStatus:
    ACTIVE = "ACTIVE"
    HIDDEN = "HIDDEN"
    SOLD_OUT = "SOLD_OUT"


class HarvestSlotStatus:
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class ReservationStatus:
    RESERVED = "RESERVED"
    ORDERED = "ORDERED"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"


class OrderStatus:
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAID = "PAID"
    PROCUREMENT_REQUESTED = "PROCUREMENT_REQUESTED"
    PROCUREMENT_APPROVED = "PROCUREMENT_APPROVED"
    PROCUREMENT_PARTIAL_APPROVED = "PROCUREMENT_PARTIAL_APPROVED"
    PROCUREMENT_REJECTED = "PROCUREMENT_REJECTED"
    QUALITY_CHECKING = "QUALITY_CHECKING"
    READY_TO_SHIP = "READY_TO_SHIP"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    REFUNDED = "REFUNDED"
    CANCELED = "CANCELED"


class OrderItemStatus:
    ORDERED = "ORDERED"
    PROCUREMENT_REQUESTED = "PROCUREMENT_REQUESTED"
    APPROVED = "APPROVED"
    PARTIAL_APPROVED = "PARTIAL_APPROVED"
    REJECTED = "REJECTED"
    QUALITY_CHECKED = "QUALITY_CHECKED"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    REFUNDED = "REFUNDED"


class PaymentMethod:
    MOCK_CARD = "MOCK_CARD"


class PaymentStatus:
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
    REFUNDED = "REFUNDED"


class ProcurementStatus:
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    PARTIAL_APPROVED = "PARTIAL_APPROVED"
    REJECTED = "REJECTED"


class QualityModelDecision:
    PASS = "PASS"
    REVIEW = "REVIEW"
    HOLD = "HOLD"


class QualityOwnerDecision:
    PASS = "PASS"
    HOLD = "HOLD"


class ShipmentStatus:
    READY = "READY"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"


class ReturnStatus:
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REFUNDED = "REFUNDED"


class RefundStatus:
    REQUESTED = "REQUESTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EmailVerificationPurpose:
    SIGNUP = "SIGNUP"
    RESET_PASSWORD = "RESET_PASSWORD"
